numprocs=6

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch5/v6_batch5_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v6_batch5/v6_batch5_netParams.py
  Number of cells on node 5: 1924 
  Number of connections on node 5: 132997 
  Number of synaptic contacts on node 5: 486181 
  Number of stims on node 5: 0 
Recording 5 traces of 1 types on node 5
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x7f7c43dca0a0>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x7f7c43dcae60>)

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch5/v6_batch5_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v6_batch5/v6_batch5_netParams.py
  Number of cells on node 3: 1925 
  Number of connections on node 3: 132670 
  Number of synaptic contacts on node 3: 485485 
  Number of stims on node 3: 0 
Recording 12 traces of 1 types on node 3
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x7ff1122e1370>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x7ff1122e10f0>)

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch5/v6_batch5_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v6_batch5/v6_batch5_netParams.py
  Number of cells on node 4: 1924 
  Number of connections on node 4: 132380 
  Number of synaptic contacts on node 4: 487151 
  Number of stims on node 4: 0 
Recording 20 traces of 1 types on node 4
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x7f68a34d9870>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x7f68a34d9460>)

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch5/v6_batch5_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v6_batch5/v6_batch5_netParams.py
  Number of cells on node 2: 1925 
  Number of connections on node 2: 133679 
  Number of synaptic contacts on node 2: 488323 
  Number of stims on node 2: 0 
Recording 12 traces of 1 types on node 2
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x7fd49e678370>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x7fd49e6780f0>)

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch5/v6_batch5_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v6_batch5/v6_batch5_netParams.py
  Number of cells on node 1: 1925 
  Number of connections on node 1: 131993 
  Number of synaptic contacts on node 1: 486658 
  Number of stims on node 1: 0 
Recording 10 traces of 1 types on node 1
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x7f6925bd4be0>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'"), <traceback object at 0x7f6925bd47d0>)

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch5/v6_batch5_0_0_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v6_batch5/v6_batch5_netParams.py

Start time:  2021-12-05 01:08:24.903975

Creating network of 14 cell populations on 6 hosts...
  Number of cells on node 0: 1925 
  Done; cell creation time = 1.84 s.
Making connections...
  Number of connections on node 0: 132031 
  Number of synaptic contacts on node 0: 483212 
  Done; cell connection time = 787.12 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.02 s.
Recording 11 traces of 1 types on node 0

Gathering data...
  Done; gather time = 43.27 s.

Analyzing...
  Cells: 11548
  Connections: 795750 (68.91 per cell)
  Synaptic contacts: 2917010 (252.60 per cell)
Saving output as ../data/v6_batch5/v6_batch5_0_0.json  ... 
Finished saving!
  Done; saving time = 0.07 s.
  Done; plotting time = 0.00 s

Total time = 833.95 s

End time:  2021-12-05 01:22:18.850215
Plotting connectivity matrix...
Saving figure data as ../data/v6_batch5/v6_batch5_0_0_pop_numConns_matrix.json ... 
Plotting connectivity matrix...
Saving figure data as ../data/v6_batch5/v6_batch5_0_0_pop_convergence_matrix.json ... 
[mpiexec@fernando-Nitro5] Sending Ctrl-C to processes as requested
[mpiexec@fernando-Nitro5] Press Ctrl-C again to force abort
