numprocs=8

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_5_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_5_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_5_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_5_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_5_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_5_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_5_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_5_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py

Start time:  2021-08-19 14:34:39.578333
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py

Creating network of 55 cell populations on 8 hosts...
  Number of cells on node 5: 3918 
  Number of cells on node 0: 3919 
  Done; cell creation time = 25.31 s.
Making connections...
  Number of cells on node 2: 3918 
  Number of cells on node 3: 3918 
  Number of cells on node 7: 3918 
  Number of cells on node 4: 3918 
  Number of cells on node 1: 3919 
  Number of cells on node 6: 3918 
  Number of connections on node 4: 109520 
  Number of synaptic contacts on node 4: 764852 
  Number of connections on node 6: 108451 
  Number of synaptic contacts on node 6: 760562 
  Number of connections on node 2: 109653 
  Number of synaptic contacts on node 2: 766630 
  Number of connections on node 5: 109197 
  Number of synaptic contacts on node 5: 767234 
  Number of connections on node 1: 108489 
  Number of synaptic contacts on node 1: 756584 
  Number of connections on node 3: 109927 
  Number of synaptic contacts on node 3: 766428 
  Number of connections on node 0: 108519 
  Number of synaptic contacts on node 0: 761142 
  Done; cell connection time = 1256.29 s.
  Number of connections on node 7: 109408 
  Number of synaptic contacts on node 7: 762000 

Gathering data...
  Done; gather time = 88.75 s.

Analyzing...
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f7546da82c8>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f7f94ba02c8>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f6ef5d542c8>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7fb457a30308>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7fa1d71eb2c8>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f91fde98308>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f6ae0f27348>)
  Cells: 31346
  Connections: 873164 (27.86 per cell)
  Synaptic contacts: 6105432 (194.78 per cell)
Plotting connectivity matrix...
Saving figure data as ../data/v6_batch1/v6_batch1_5_pop_numConns_matrix.json ... 
