numprocs=8

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_3_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_3_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_3_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_3_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_3_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_3_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_3_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_3_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py

Start time:  2021-08-19 02:29:30.024361
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py

Creating network of 55 cell populations on 8 hosts...
  Number of cells on node 0: 3919 
  Done; cell creation time = 23.69 s.
Making connections...
  Number of cells on node 7: 3918 
  Number of cells on node 5: 3918 
  Number of cells on node 3: 3918 
  Number of cells on node 6: 3918 
  Number of cells on node 4: 3918 
  Number of cells on node 1: 3919 
  Number of cells on node 2: 3918 
  Number of connections on node 2: 38844 
  Number of synaptic contacts on node 2: 901030 
  Number of connections on node 0: 39178 
  Number of synaptic contacts on node 0: 908882 
  Number of connections on node 7: 39266 
  Number of synaptic contacts on node 7: 909250 
  Number of connections on node 4: 39366 
  Number of synaptic contacts on node 4: 914956 
  Number of connections on node 6: 39003 
  Number of synaptic contacts on node 6: 906634 
  Number of connections on node 1: 39134 
  Number of synaptic contacts on node 1: 909960 
  Number of connections on node 5: 39112 
  Number of synaptic contacts on node 5: 907700 
  Number of connections on node 3: 39093 
  Number of synaptic contacts on node 3: 906860 
  Done; cell connection time = 815.06 s.

Gathering data...
  Done; gather time = 102.77 s.

Analyzing...
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f0955d82308>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7fb1e95e0348>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f08c9ab2308>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f5c8bf6e308>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f447dceb308>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f6627037348>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f06e56a82c8>)
  Cells: 31346
  Connections: 312996 (9.99 per cell)
  Synaptic contacts: 7265272 (231.78 per cell)
Plotting connectivity matrix...
Saving figure data as ../data/v6_batch0/v6_batch0_3_pop_numConns_matrix.json ... 
