numprocs=8

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_4_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_4_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_4_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_4_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_4_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_4_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_4_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_4_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py

Start time:  2021-08-19 02:29:27.593285
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py

Creating network of 55 cell populations on 8 hosts...
  Number of cells on node 5: 3918 
  Number of cells on node 6: 3918 
  Number of cells on node 7: 3918 
  Number of cells on node 1: 3919 
  Number of cells on node 3: 3918 
  Number of cells on node 2: 3918 
  Number of cells on node 4: 3918 
  Number of cells on node 0: 3919 
  Done; cell creation time = 24.23 s.
Making connections...
  Number of connections on node 4: 39294 
  Number of synaptic contacts on node 4: 911424 
  Number of connections on node 6: 39410 
  Number of synaptic contacts on node 6: 914118 
  Number of connections on node 0: 38709 
  Number of synaptic contacts on node 0: 898472 
  Number of connections on node 5: 39485 
  Number of synaptic contacts on node 5: 914408 
  Number of connections on node 3: 39156 
  Number of synaptic contacts on node 3: 906784 
  Number of connections on node 2: 38681 
  Number of synaptic contacts on node 2: 895264 
  Number of connections on node 7: 38941 
  Number of synaptic contacts on node 7: 903764 
  Done; cell connection time = 821.45 s.
  Number of connections on node 1: 39096 
  Number of synaptic contacts on node 1: 907168 

Gathering data...
  Done; gather time = 104.43 s.

Analyzing...
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f6923278348>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f6bc5ba2308>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f1f95407348>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7ff3c4c3d2c8>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7fd8ebe58308>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f2d317a1308>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f7fa84cf308>)
  Cells: 31346
  Connections: 312772 (9.98 per cell)
  Synaptic contacts: 7251402 (231.33 per cell)
Plotting connectivity matrix...
Saving figure data as ../data/v6_batch0/v6_batch0_4_pop_numConns_matrix.json ... 
