numprocs=4

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batchb/v6_batchb_6_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batchb/v6_batchb_6_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batchb/v6_batchb_6_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batchb/v6_batchb_6_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v6_batchb/v6_batchb_netParams.py
Importing netParams from ../data/v6_batchb/v6_batchb_netParams.py
Importing netParams from ../data/v6_batchb/v6_batchb_netParams.py
Importing netParams from ../data/v6_batchb/v6_batchb_netParams.py

Start time:  2021-08-19 21:34:33.959314

Creating network of 55 cell populations on 4 hosts...
  Number of cells on node 2: 7836 
  Number of cells on node 0: 7837 
  Done; cell creation time = 34.48 s.
Making connections...
  Number of cells on node 1: 7837 
  Number of cells on node 3: 7836 
  Number of connections on node 3: 228732 
  Number of synaptic contacts on node 3: 1731390 
  Number of connections on node 0: 230520 
  Number of synaptic contacts on node 0: 1744094 
  Number of connections on node 2: 226374 
  Number of synaptic contacts on node 2: 1714586 
  Number of connections on node 1: 227727 
  Number of synaptic contacts on node 1: 1725132 
  Done; cell connection time = 1680.43 s.

Gathering data...
  Done; gather time = 113.53 s.

Analyzing...
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f9b65c98308>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7fc54f5692c8>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f14165cd2c8>)
  Cells: 31346
  Connections: 913353 (29.14 per cell)
  Synaptic contacts: 6915202 (220.61 per cell)
Plotting connectivity matrix...
Saving figure data as ../data/v6_batchb/v6_batchb_6_pop_numConns_matrix.json ... 
