numprocs=8

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_6_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_6_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_6_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_6_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_6_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_6_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_6_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch1/v6_batch1_6_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py

Start time:  2021-08-19 14:34:37.143717
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py
Importing netParams from ../data/v6_batch1/v6_batch1_netParams.py

Creating network of 55 cell populations on 8 hosts...
  Number of cells on node 2: 3918 
  Number of cells on node 0: 3919 
  Done; cell creation time = 24.81 s.
Making connections...
  Number of cells on node 3: 3918 
  Number of cells on node 7: 3918 
  Number of cells on node 4: 3918 
  Number of cells on node 5: 3918 
  Number of cells on node 6: 3918 
  Number of cells on node 1: 3919 
  Number of connections on node 6: 108304 
  Number of synaptic contacts on node 6: 759200 
  Number of connections on node 2: 109401 
  Number of synaptic contacts on node 2: 762410 
  Number of connections on node 3: 110170 
  Number of synaptic contacts on node 3: 767574 
  Number of connections on node 0: 107531 
  Number of synaptic contacts on node 0: 751894 
  Number of connections on node 4: 108906 
  Number of synaptic contacts on node 4: 763372 
  Number of connections on node 5: 108545 
  Number of synaptic contacts on node 5: 757986 
  Number of connections on node 1: 108313 
  Number of synaptic contacts on node 1: 758466 
  Number of connections on node 7: 109613 
  Number of synaptic contacts on node 7: 764438 
  Done; cell connection time = 1283.45 s.

Gathering data...
  Done; gather time = 87.00 s.

Analyzing...
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7fb7cc4222c8>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f0c466952c8>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7feff41942c8>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7fafdff652c8>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f60f2eb0308>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7fa9682f5348>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7fa71895b308>)
  Cells: 31346
  Connections: 870783 (27.78 per cell)
  Synaptic contacts: 6085340 (194.13 per cell)
Plotting connectivity matrix...
Saving figure data as ../data/v6_batch1/v6_batch1_6_pop_numConns_matrix.json ... 
