numprocs=8

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_2_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_2_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_2_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_2_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_2_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_2_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_2_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file ../data/v6_batch0/v6_batch0_2_cfg.json ... 
Loading simConfig...
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py
Importing netParams from ../data/v6_batch0/v6_batch0_netParams.py

Start time:  2021-08-19 02:29:30.771930

Creating network of 55 cell populations on 8 hosts...
  Number of cells on node 4: 3918 
  Number of cells on node 0: 3919 
  Done; cell creation time = 26.42 s.
Making connections...
  Number of cells on node 1: 3919 
  Number of cells on node 2: 3918 
  Number of cells on node 3: 3918 
  Number of cells on node 7: 3918 
  Number of cells on node 6: 3918 
  Number of cells on node 5: 3918 
  Number of connections on node 6: 39300 
  Number of synaptic contacts on node 6: 913382 
  Number of connections on node 0: 38787 
  Number of synaptic contacts on node 0: 900200 
  Number of connections on node 5: 39182 
  Number of synaptic contacts on node 5: 907904 
  Number of connections on node 4: 39463 
  Number of synaptic contacts on node 4: 915140 
  Number of connections on node 2: 39026 
  Number of synaptic contacts on node 2: 904800 
  Number of connections on node 7: 38941 
  Number of synaptic contacts on node 7: 904646 
  Number of connections on node 1: 39082 
  Number of synaptic contacts on node 1: 905910 
  Number of connections on node 3: 39059 
  Number of synaptic contacts on node 3: 904320 
  Done; cell connection time = 823.27 s.

Gathering data...
  Done; gather time = 105.61 s.

Analyzing...
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f3339735348>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f666112b308>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f078999b308>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f375735b348>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f5be05972c8>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7fc09e38b308>)
Plotting connectivity matrix...
  There was an exception in plotConn(): 
    'Network' object has no attribute 'allCells' 
    (<class 'AttributeError'>, AttributeError("'Network' object has no attribute 'allCells'",), <traceback object at 0x7f913bbc2308>)
  Cells: 31346
  Connections: 312840 (9.98 per cell)
  Synaptic contacts: 7256302 (231.49 per cell)
Plotting connectivity matrix...
Saving figure data as ../data/v6_batch0/v6_batch0_2_pop_numConns_matrix.json ... 
